name: spots_app
description: Main SPOTS Flutter application
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Local packages
  spots_core:
    path: ../spots_core
  spots_data:
    path: ../spots_data
  spots_network:
    path: ../spots_network
  spots_ai:
    path: ../spots_ai
  spots_ml:
    path: ../spots_ml
  
  # UI dependencies
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_map: ^7.0.0
  get_it: ^8.0.3
  
  # Platform integration
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
